version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MarketPuanDB
      POSTGRES_USER: ozanp
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5432:5432"
